global using Kader_System.Domain.Dtos.Request.Auth;
global using Kader_System.Services.IServices.Auth;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using static Kader_System.Domain.Constants.SD;
global using AutoMapper;
global using Kader_System.Domain.Dtos.Response.Auth;
global using Kader_System.Domain.Models.Auth;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Kader_System.Domain.Constants;
global using Kader_System.Domain.Dtos.Response;
global using Kader_System.Domain.Dtos.Response.Perm;
global using Kader_System.Domain.Extensions;
global using Kader_System.Domain.Dtos.Request.Perm;
global using Kader_System.Services.IServices.Shared;
global using Kader_System.Domain.Dtos.Request.Shared;
global using Kader_System.Domain.Models.Shared;
global using Kader_System.Domain.DTOs.Response.Shared;
